# Generated by Django 2.2.5 on 2020-03-12 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShuttleHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_id', models.CharField(max_length=10)),
                ('boarding_time', models.DateField(auto_now_add=True)),
                ('staff_id', models.CharField(max_length=7)),
            ],
        ),
    ]
