# Generated by Django 2.2.5 on 2020-03-12 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_shuttlehistory'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShuttleHistory',
            new_name='ShuttleCheckIn',
        ),
    ]
