# Generated by Django 2.2.5 on 2020-03-15 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_auto_20200312_1542'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttlecheckin',
            name='boarding_time',
            field=models.DateField(editable=False),
        ),
    ]
