# Generated by Django 2.2.5 on 2020-03-15 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20200315_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttlecheckin',
            name='boarding_time',
            field=models.DateField(),
        ),
    ]
