# Generated by Django 2.2.5 on 2020-03-15 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_auto_20200315_2311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttlecheckin',
            name='boarding_time',
            field=models.DateTimeField(),
        ),
    ]
