# Generated by Django 2.2.5 on 2020-03-16 05:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20200315_2314'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shuttlecheckin',
            name='vehicle_id',
            field=models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(7)]),
        ),
    ]
